### ISSUE TITLE
wrong acknowledgement in pic driver

### ISSUE THREAD

**Issue by jgiron42** [shadokos/kfs#175]
when handling slave pic interrupts, the acknowledgement need to be send to both master and slave pic.

**Comment by riblanc** [comment]
![image](https://github.com/user-attachments/assets/f379fb7b-5b63-4dfa-9a55-95e30576fb22)
*c.f. [8259A Manual reference](https://pdos.csail.mit.edu/6.828/2010/readings/hardware/8259A.pdf)*
